# Generated by Django 2.0.3 on 2018-04-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestphone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_11',
            name='id',
        ),
        migrations.RemoveField(
            model_name='table_12',
            name='id',
        ),
        migrations.RemoveField(
            model_name='table_13',
            name='id',
        ),
        migrations.RemoveField(
            model_name='table_14',
            name='id',
        ),
        migrations.AlterField(
            model_name='table_11',
            name='model_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='table_12',
            name='model_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='table_13',
            name='model_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='table_14',
            name='model_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
